### ISSUE TITLE
Development environment doesn't work out of the box

### ISSUE THREAD

**Issue by keyan** [edgurgel/verk_web#30]
Not sure if this is an issue with my setup but trying to run the `master` branch of VerkWeb locally doesn't work for me:

```
$ mix deps.get
$ npm install && bower install
$ mix phoenix.server

[info] GET /
[debug] Processing by VerkWeb.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 500 in 12ms
[error] #PID<0.2415.0> running VerkWeb.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        (stdlib) :ets.select(:queue_stats, [{{:"$1", :"$2", :"$3", :"$4", :_, :_}, [], [{{:"$1", :"$2", :"$3", :"$4"}}]}])
        (verk) lib/verk/queue_stats_counters.ex:23: Verk.QueueStatsCounters.all/0
        (verk) lib/verk/queue_stats.ex:22: Verk.QueueStats.all/0
        (verk_web) web/controllers/page_controller.ex:6: VerkWeb.PageController.index/2
        (verk_web) web/controllers/page_controller.ex:1: VerkWeb.PageController.action/2
        (verk_web) web/controllers/page_controller.ex:1: VerkWeb.PageController.phoenix_controller_pipeline/2
        (verk_web) lib/phoenix/router.ex:261: VerkWeb.Router.dispatch/2
        (verk_web) web/router.ex:1: VerkWeb.Router.do_call/2
        (verk_web) lib/verk_web/endpoint.ex:1: VerkWeb.Endpoint.phoenix_pipeline/1
        (verk_web) lib/plug/debugger.ex:123: VerkWeb.Endpoint."call (overridable 3)"/2
        (verk_web) lib/phoenix/endpoint/render_errors.ex:34: VerkWeb.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

Is there something else I need to do to run this in development?

**Comment by edgurgel** [comment]
We need Verk running. My current approach is:

local.exs
```elixir
spawn fn ->
  Verk.Supervisor.start_link
  receive do
    _ -> :ok
  end
end
```

`iex -S mix local.exs`

What if we check [here](https://github.com/edgurgel/verk_web/blob/master/lib/verk_web.ex#L5) for a configuration that by default is `false` to start `Verk.Supervisor` ?

It would be true here [config/dev.exs](https://github.com/edgurgel/verk_web/blob/master/config/dev.exs)

Not sure what's the best approach here honestly...
